// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVzrcHHZC_al-koQkSo0CGnKIZMVf_rA',
    appId: '1:948290139673:web:737404199294fa66545c88',
    messagingSenderId: '948290139673',
    projectId: 'pot-project-10311',
    authDomain: 'pot-project-10311.firebaseapp.com',
    storageBucket: 'pot-project-10311.firebasestorage.app',
    measurementId: 'G-T0WK3X4HVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNTc7A0fmTkiQYSHs1PGAFzm9haKWIrQ',
    appId: '1:948290139673:android:ad56e4fff5458bc3545c88',
    messagingSenderId: '948290139673',
    projectId: 'pot-project-10311',
    storageBucket: 'pot-project-10311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeXF7RcSZRFpCsx4jws2MLAndmWNukOXo',
    appId: '1:948290139673:ios:fb157ab891c4c3fe545c88',
    messagingSenderId: '948290139673',
    projectId: 'pot-project-10311',
    storageBucket: 'pot-project-10311.firebasestorage.app',
    iosBundleId: 'com.example.hahaha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeXF7RcSZRFpCsx4jws2MLAndmWNukOXo',
    appId: '1:948290139673:ios:fb157ab891c4c3fe545c88',
    messagingSenderId: '948290139673',
    projectId: 'pot-project-10311',
    storageBucket: 'pot-project-10311.firebasestorage.app',
    iosBundleId: 'com.example.hahaha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOVzrcHHZC_al-koQkSo0CGnKIZMVf_rA',
    appId: '1:948290139673:web:4fe9ddbb8c6cb979545c88',
    messagingSenderId: '948290139673',
    projectId: 'pot-project-10311',
    authDomain: 'pot-project-10311.firebaseapp.com',
    storageBucket: 'pot-project-10311.firebasestorage.app',
    measurementId: 'G-95VSDMX0C0',
  );
}
